# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alakela' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alakela
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Cosmos', '~> 19.0'
pod 'ImageSlideshow', '~> 1.8.1'
pod 'ImageSlideshow/SDWebImage'
pod 'Google-Mobile-Ads-SDK'
pod 'MOLH'

end
